config/routes.rb
Rails.application.routes.draw do

  get 'appointments/patient_appointments'
  post 'appointments/patient_create'

  get 'appointments/patient_appointments_with_diagnostic'
  get 'appointments/new_patient'
  get 'appointments/appointment_invoice'
  get 'patients/patients_with_appointments'
  get 'patients/patients_with_appointments_with_diagnostic'
  get 'physicians/physicians_with_appointments'
  get 'appointments/physician_appointments'

  get 'appointments/physician_appointments_with_invoiced_amount'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  get 'welcome/index'
  get 'welcome/patient'
  get 'welcome/office_worker'
  get 'welcome/physician'
  get 'welcome/system_administrator'
  get 'welcome/invoice_pdf'

  root 'welcome#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
   # Diagnostic.destroy_all
   # require 'csv'

   # csv_text = File.read('/vagrant/projects/diagnosticcodes.csv')
   # csv = CSV.parse(csv_text, :headers => true)
   # csv.each do |row|
    #  Diagnostic.create!(row.to_hash)
    #end
  end

  def patient

  end

  def physician

  end

  def office_worker


  end

  def system_administrator

  end


end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<h1>Welcome!</h1>
<p>
  <h1>Please Select your Role</h1>
    <ul>
      <li><%= link_to "Patient",welcome_patient_path%></li>
      <li><%= link_to "Office Worker",welcome_office_worker_path%></li>
      <li><%= link_to "Physician",welcome_physician_path%></li>
      <li><%= link_to "System Administrator",welcome_system_administrator_path%></li>


    </ul>

</p>

app/views/welcome/office_worker.html.erb
<h1>Hello Office Worker</h1>
<p>
<ul>
  <li><%= link_to "View Patients with pending invoices", patients_patients_with_appointments_with_diagnostic_path%></li>

</ul>

</p>

<%= link_to 'Home', welcome_index_path %>

app/views/welcome/patient.html.erb
<h1>Hello Patient</h1>
<p>
<h1>What would you like to do?</h1>
<ul>
  <li><%= link_to 'Create New Patient',new_patient_path %></li>

  <li><%= link_to 'New Appointment',appointments_new_patient_path %></li>
  <li><%= link_to 'Show  appointments',patients_patients_with_appointments_path %></li>

  <li><%= link_to "Home",welcome_index_path%></li>


</ul>

</p>

app/views/welcome/physician.html.erb
<h1>Hello Doctor</h1>
<p>
<h1></h1>
<ul>

  <li><%= link_to "View appointments",physicians_physicians_with_appointments_path%></li>

  <li><%= link_to "Home",welcome_index_path%></li>


</ul>

app/views/welcome/system_administrator.html.erb
<h1> <c> Hello Admin </c></h1>
<p>
<h2>What would you like to do?</h2>
<ul>
  <li><%= link_to "View/Edit Diagnostics ",diagnostics_path%></li>
  <li><%= link_to "View/Edit Physicians",physicians_path%></li>

    <br>
  <br>

  <li><%= link_to "View physicians appoinments with invoiced amount",appointments_physician_appointments_with_invoiced_amount_path%></li>

  <li><%= link_to "Home",welcome_index_path%></li>

</ul>