config/routes.rb
Rails.application.routes.draw do

  get 'appointments/patient_appointments'
  post 'appointments/patient_create'

  get 'appointments/patient_appointments_with_diagnostic'
  get 'appointments/new_patient'
  get 'appointments/appointment_invoice'
  get 'patients/patients_with_appointments'
  get 'patients/patients_with_appointments_with_diagnostic'
  get 'physicians/physicians_with_appointments'
  get 'appointments/physician_appointments'

  get 'appointments/physician_appointments_with_invoiced_amount'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  get 'welcome/index'
  get 'welcome/patient'
  get 'welcome/office_worker'
  get 'welcome/physician'
  get 'welcome/system_administrator'
  get 'welcome/invoice_pdf'

  root 'welcome#index'

end

app/models/patient.rb
class Patient < ActiveRecord::Base
  has_many :appointments

  has_many :diagnostics, through: :appointments

  def self.with_appointments
    self.includes(:appointments).where.not(appointments: { id: nil})
  end


  def self.with_appointments_with_diagnostic
    self.includes(:diagnostics).where.not(diagnostics: { id: nil})
  end
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
  end

  def patients_with_appointments
    @patients = Patient.with_appointments
  end





  def patients_with_appointments_with_diagnostic
    @patients = Patient.with_appointments_with_diagnostic
  end



  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :address, :phoneNumber)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= form_for(@patient) do |f| %>
  <% if @patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% @patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phoneNumber %><br>
    <%= f.text_field :phoneNumber %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing patient</h1>

<%= render 'form' %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phoneNumber %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Patient', new_patient_path %>
<%= link_to 'Home', welcome_index_path %>

app/views/patients/new.html.erb
<h1>New patient</h1>

<%= render 'form' %>

<%= link_to 'Back', patients_path %>

app/views/patients/patients_with_appointments.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phoneNumber %></td>
        <td><%= link_to 'show appointments', appointments_patient_appointments_path(:id => patient.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', welcome_patient_path %>



<%= link_to 'Home', welcome_index_path %>

app/views/patients/patients_with_appointments_with_diagnostic.html.erb
<h1>Listing patients</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phonenumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.address %></td>
        <td><%= patient.phoneNumber %></td>
        <td><%= link_to 'show appointments', appointments_patient_appointments_with_diagnostic_path(:id => patient.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', welcome_office_worker_path %>


<%= link_to 'Home', welcome_index_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Phonenumber:</strong>
  <%= @patient.phoneNumber %>
</p>

<%= link_to 'Edit', edit_patient_path(@patient) %> |
<%= link_to 'Back', patients_path %>