config/routes.rb
Rails.application.routes.draw do

  get 'appointments/patient_appointments'
  post 'appointments/patient_create'

  get 'appointments/patient_appointments_with_diagnostic'
  get 'appointments/new_patient'
  get 'appointments/appointment_invoice'
  get 'patients/patients_with_appointments'
  get 'patients/patients_with_appointments_with_diagnostic'
  get 'physicians/physicians_with_appointments'
  get 'appointments/physician_appointments'

  get 'appointments/physician_appointments_with_invoiced_amount'

  resources :appointments

  resources :diagnostics

  resources :physicians

  resources :patients

  get 'welcome/index'
  get 'welcome/patient'
  get 'welcome/office_worker'
  get 'welcome/physician'
  get 'welcome/system_administrator'
  get 'welcome/invoice_pdf'

  root 'welcome#index'

end

app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :patient
  belongs_to :physician
  belongs_to :diagnostic

  def self.with_diagnostic
    self.where.not(diagnostic:nil)
  end


  def self.with_diagnostic_for_patient(patient_id)
    self.where.not(diagnostic:nil).where(:patient=>Patient.find(patient_id))
  end

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
  end


  def patient_appointments
    @appointments = Appointment.where(:patient => Patient.find(params[:id]))
  end

  def patient_appointments_with_diagnostic
    @appointments = Appointment.with_diagnostic_for_patient(params[:id])
  end

  def physician_appointments_with_invoiced_amount
    @appointments = Appointment.with_diagnostic.order("physician_id asc")
  end


  def appointment_invoice
    appointment= Appointment.find(params[:id])
    html = render_to_string(:layout => "appointment_invoice.html", :locals => {:appointment => appointment})
    pdf=WickedPdf.new.pdf_from_string(html)
    send_data(pdf, :filename => "invoice"+appointment.id.to_s+".pdf", :disposition => 'attachment')
  end

  def physician_appointments
    @appointments = Appointment.where(:physician => Physician.find(params[:id]))
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/new_patient
  def new_patient
    @appointment = Appointment.new
  end


  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create

    @appointment = Appointment.new(appointment_params)
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  def occupied_date(new_app)
    occupied=false
    Appointment.where(:physician_id == new_app.physician_id).each do |app|

      timediff=TimeDifference.between(new_app.start,app.start).in_minutes.abs
      puts "time diff:"+timediff.to_s+ " new_app"+new_app.start.to_s+ " other app:"+app.start.to_s
      if ((timediff)) < 30
        occupied=true
      end
    end
    return occupied
  end

  # POST /appointments
  # POST /appointments.json
  def patient_create
    @appointment = Appointment.new(appointment_params)
    hour=params["hour"].to_i
    year=params["year"].to_i
    month=params["month"].to_i
    day=params["day"].to_i

    puts "---------year:"+year.to_s
    puts "---------month:"+month.to_s
    puts "---------day:"+day.to_s

    minutes=params["minutes"].to_i
    start=DateTime.new(year,month,day,hour,minutes,0,'+0')
    @appointment.start=start

    respond_to do |format|
      #validate the date
      if @appointment.start.saturday? || @appointment.start.sunday?

        @appointment.errors.add(:start, "Appointment cannot be on weekend")
        format.html { render :new_patient }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }

        #past date


      elsif @appointment.start.past?
        @appointment.errors.add(:start, "past date")
        format.html { render :new_patient }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      elsif occupied_date(@appointment)
        @appointment.errors.add(:start, "Occupied date")
        format.html { render :new_patient}
        format.json { render json: @appointment.errors, status: :unprocessable_entity }

        elsif @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new_patient }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_appointment
    @appointment = Appointment.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def appointment_params
    params.require(:appointment).permit(:notes, :start, :physician_id, :patient_id, :diagnostic_id)
  end
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_for(@appointment) do |f| %>
  <% if @appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% @appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :start %><br>
    <%= f.datetime_select :start, { :include_blank => true, :start_year => 2014, :minute => 30} %>
  </div>


  <div class="field">

    <%= f.label :physician_id %><br>
    <%= f.collection_select :physician_id, Physician.all, :id, :name %>
  </div>
  <div class="field">
    <%= f.label :patient_id %><br>
    <%= f.collection_select :patient_id, Patient.all, :id, :name %>

  </div>

    <div class="field">

      <%= f.label :notes %><br>
      <%= f.collection_select :physician_id, Physician.all, :id, :name %>
    </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>


<%= link_to 'Back', welcome_patient_path %>


<%= link_to 'Home', welcome_index_path %>

app/views/appointments/_patient_form.html.erb
<%= form_for(@appointment, :url => {:controller=> 'appointments',:action => 'patient_create'}) do |f| %>
    <% if @appointment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

          <ul>
            <% @appointment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :start %><br>
      <%= f.label :day %>
      <select name="day">
        <option value="1">1</option>
        <option value="2">2</option>
        <option value="3">3</option>
        <option value="4">4</option>
        <option value="5">5</option>
        <option value="6">6</option>
        <option value="7">7</option>
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
        <option value="11">11</option>
        <option value="12">12</option>
        <option value="13">13</option>
        <option value="14">14</option>
        <option value="15">15</option>
        <option value="16">16</option>
        <option value="17">17</option>
        <option value="18">18</option>
        <option value="19">19</option>
        <option value="20">20</option>
        <option value="21">21</option>
        <option value="22">22</option>
        <option value="23">23</option>
        <option value="24">24</option>
        <option value="25">25</option>
        <option value="26">26</option>
        <option value="27">27</option>
        <option value="28">28</option>
        <option value="29">29</option>
        <option value="30">30</option>
        <option value="31">31</option>

      </select>
      -
      <select name="month">
        <option value="1">Jan</option>
        <option value="2">Feb</option>
        <option value="3">Mar</option>
        <option value="4">Apr</option>
        <option value="5">May</option>
        <option value="6">Jun</option>
        <option value="7">July</option>
        <option value="8">Aug</option>
        <option value="9">Sept</option>
        <option value="10">Oct</option>
        <option value="11">Nov</option>
        <option value="12">Dec</option>

      </select>
      -
      <select name="year">
        <option value="2014">2014</option>
        <option value="2015">2015</option>
        <option value="2016">2016</option>
        <option value="2017">2017</option>
        <option value="2018">2018</option>

      </select>



      <%= f.label :time %>
      <select name="hour">
        <option value="8">8</option>
        <option value="9">9</option>
        <option value="10">10</option>
        <option value="11">11</option>
        <option value="12">12</option>
        <option value="13">1</option>
        <option value="14">2</option>
        <option value="15">3</option>
        <option value="16">4</option>
      </select>
      :
      <select name="minutes">
        <option value="0">00</option>
        <option value="30">30</option>
      </select>

    </div>


    <div class="field">

      <%= f.label :physician_id %><br>
      <%= f.collection_select :physician_id, Physician.where(:active => true),:id,:name %>

    </div>
    <div class="field">
      <%= f.label :patient_id %><br>
      <%= f.collection_select :patient_id, Patient.all, :id, :name %>

    </div>

    <div class="field">

      <%= f.label :reasons %><br>
      <%= f.text_field :reasons %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/appointments/_physician_form.html.erb
<%= form_for(@appointment) do |f| %>
    <% if @appointment.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

          <ul>
            <% @appointment.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>


    <div class="field">
      <%= f.label :start %><br>

      <%= f.datetime_select :start,{:minute => [0,30]}, :prompt => { :day => 'select day', :include_blank => true, :start_year => 2014}%>
    </div>


    <div class="field">
      <%= f.label :physician_id %><br>
      <%= f.collection_select :physician_id, Physician.all, :id, :name %>
    </div>
    <div class="field">
      <%= f.label :patient_id %><br>
      <%= f.collection_select :patient_id, Patient.all, :id, :name %>
    </div>

    <div class="field">

      <%= f.label :reasons %><br>
      <%= f.text_field :reasons,:readonly =>true %>
    </div>


    <div class="field">

      <%= f.label :notes %><br>
      <%= f.text_field :notes %>
    </div>

    <div class="field">
      <%= f.label :diagnostic_id %><br>
      <%= f.collection_select :diagnostic_id, Diagnostic.all, :id, :description %>
    </div>

    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

<%= link_to 'Back', welcome_physician_path %>


<%= link_to 'Home', welcome_index_path %>

app/views/appointments/appointment_invoice.html.erb
fsdjklkl
asdfjkljklasdfjklasdf
asdfofasdjhçasdfjkasdfjkl
sdfjklsdfjkl
<h1> sadjklfsdjklsdfsfda</h1>

app/views/appointments/edit.html.erb
<h1>Editing appointment</h1>

<%= render 'physician_form' %>

<%= link_to 'Show', @appointment %> |

app/views/appointments/index.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Start</th>
      <th>Physician</th>
      <th>Patient</th>
      <th>Diagnostic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.notes %></td>
        <td><%= appointment.start %></td>
        <td><%= appointment.physician_id %></td>
        <td><%= appointment.patient_id %></td>
        <td><%= appointment.diagnostic_id %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
        <td><%= link_to 'Destroy', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>


<%= link_to 'Back', welcome_physician_path %>


<%= link_to 'Home', welcome_index_path %>

app/views/appointments/new.html.erb
<h1>New appointment</h1>

<%= render 'form' %>

<%= link_to 'Back', welcome_patient_path %>
<%= link_to 'Home', welcome_index_path %>

app/views/appointments/new_patient.html.erb
<h1>New appointment</h1>

<%= render 'patient_form' %>

<%= link_to 'Back', welcome_patient_path %>

<%= link_to 'Home', welcome_index_path %>

app/views/appointments/patient_appointments.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Start</th>
      <th>Physician</th>
      <th>Patient</th>
      <th>Diagnostic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.notes %></td>
        <td><%= appointment.start %></td>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.diagnostic_id %></td>
        <td><%= link_to 'Show', appointment %></td>
        <% diff=appointment.start.to_i - DateTime.now.to_i
           puts 'diff '+diff.to_s
           if diff > 60*60*8
        %>
        <td><%= link_to 'Cancel', appointment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', appointments_new_patient_path %>


<%= link_to 'Back', welcome_patient_path %>

<%= link_to 'Home', welcome_index_path %>

app/views/appointments/patient_appointments_with_diagnostic.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Start</th>
      <th>Physician</th>
      <th>Patient</th>
      <th>Diagnostic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.notes %></td>
        <td><%= appointment.start %></td>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.diagnostic_id %></td>
        <td><%= link_to 'Generate invoice', appointments_appointment_invoice_path(:id => appointment.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', new_appointment_path %>

<%= link_to 'Back', patients_patients_with_appointments_with_diagnostic_path %>


<%= link_to 'Home', welcome_index_path %>

app/views/appointments/patient_new.html.erb
<h1>New appointment</h1>

<%= render 'patient_form' %>

app/views/appointments/physician_appointments.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Start</th>
      <th>Physician</th>
      <th>Patient</th>
      <th>Diagnostic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.notes %></td>
        <td><%= appointment.start %></td>
        <td><%= appointment.physician.name%></td>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.diagnostic_id %></td>
        <td><%= link_to 'Show', appointment %></td>
        <td><%= link_to 'Edit', edit_appointment_path(appointment) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'Back', welcome_physician_path %>

<%= link_to 'Home', welcome_index_path %>

app/views/appointments/physician_appointments_with_invoiced_amount.html.erb
<h1>Listing appointments</h1>

<table>
  <thead>
    <tr>
      <th>Notes</th>
      <th>Start</th>
      <th>Physician</th>
      <th>Patient</th>
      <th>Diagnostic</th>
      <th>Amount invoiced</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @appointments.each do |appointment| %>
      <tr>
        <td><%= appointment.notes %></td>
        <td><%= appointment.start %></td>
        <td><%= appointment.physician.name %></td>
        <td><%= appointment.patient.name %></td>
        <td><%= appointment.diagnostic.description %></td>
        <td><%= appointment.diagnostic.price %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Appointment', appointments_new_patient_path %>


<%= link_to 'Back', welcome_system_administrator_path %>


<%= link_to 'Home', welcome_index_path %>

app/views/appointments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Notes:</strong>
  <%= @appointment.notes %>
</p>

<p>
  <strong>Start:</strong>
  <%= @appointment.start %>
</p>

<p>
  <strong>Physician:</strong>
  <%= @appointment.physician_id %>
</p>

<p>
  <strong>Patient:</strong>
  <%= @appointment.patient_id%>
</p>

<p>
  <strong>Diagnostic:</strong>
  <%= @appointment.diagnostic_id %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>




<%= link_to 'Home', welcome_index_path %>